Typo in python API: 'int' should be 'int64'
This caused the python API to incorrectly raise the exception:

TypeError: Cannot store heterogeneous maps

when one tries to put() a map attribute with key and/or value being
of type 'int64' and the map contains > 1 entries.